package repoimpact

import (
	"testing"
)

func TestClassifyPath(t *testing.T) {
	cases := []struct {
		path string
		want Subsystem
	}{
		// docs-only
		{"CONTRIBUTING.md", SubsystemDocs},
		{"apps/docs/content/docs/developers/contributing.zh.mdx", SubsystemDocs},
		{"docs/commanddeck/runbooks/LOCAL-DOGFOOD-ACCESS.md", SubsystemDocs},
		// migration
		{"server/migrations/091_add_widget.up.sql", SubsystemDatabase},
		{"server/migrations/084_command_template.down.sql", SubsystemDatabase},
		// auth / security
		{"server/internal/middleware/auth.go", SubsystemSecurityAuth},
		{"server/internal/middleware/daemon_auth.go", SubsystemSecurityAuth},
		{"packages/core/platform/auth-initializer.tsx", SubsystemSecurityAuth},
		{"apps/web/app/(auth)/login/page.tsx", SubsystemSecurityAuth},
		// command runner / execution
		{"server/internal/handler/commandrunner.go", SubsystemCommandExec},
		{"server/internal/handler/commandworkflow.go", SubsystemCommandExec},
		// runtime / daemon
		{"server/internal/daemon/manager.go", SubsystemDaemonRuntime},
		{"server/internal/handler/runtime_liveness_store.go", SubsystemDaemonRuntime},
		// infra / docker
		{"compose.yml", SubsystemInfraDocker},
		{"docker-compose.yml", SubsystemInfraDocker},
		{"apps/web/Dockerfile", SubsystemInfraDocker},
		// ci
		{".github/workflows/ci.yml", SubsystemGithubCI},
		// scripts / devtools
		{"scripts/ensure-postgres.sh", SubsystemScriptsDevtools},
		{"Makefile", SubsystemScriptsDevtools},
		// tests
		{"server/internal/handler/config_test.go", SubsystemTests},
		{"packages/core/api/client.test.ts", SubsystemTests},
		{"e2e/tests/login.spec.ts", SubsystemTests},
		// backend / frontend fallthrough
		{"server/internal/handler/config.go", SubsystemBackend},
		{"packages/core/api/client.ts", SubsystemFrontend},
		{"apps/web/app/page.tsx", SubsystemFrontend},
		// unknown
		{"weird-root-file.xyz", SubsystemUnknown},
		{"author/notes", SubsystemUnknown}, // "author" must NOT match the auth token
	}
	for _, c := range cases {
		if got := ClassifyPath(c.path); got != c.want {
			t.Errorf("ClassifyPath(%q) = %q, want %q", c.path, got, c.want)
		}
	}
}

func flagNames(flags []RiskFlag) map[string]RiskFlag {
	m := map[string]RiskFlag{}
	for _, f := range flags {
		m[f.Name] = f
	}
	return m
}

func TestRiskFlags_MigrationAndAuth(t *testing.T) {
	files := []ChangedFile{
		{Path: "server/migrations/091_widget.up.sql"},
		{Path: "server/internal/middleware/auth.go"},
		{Path: "server/internal/handler/commandrunner.go"},
		{Path: "server/internal/daemon/manager.go"},
	}
	got := flagNames(RiskFlags(files))
	for _, name := range []string{
		"migrations_touched", "auth_security_touched",
		"command_execution_touched", "runtime_daemon_touched",
		"tests_missing_for_code_change",
	} {
		if _, ok := got[name]; !ok {
			t.Errorf("expected risk flag %q to be raised", name)
		}
	}
	if got["migrations_touched"].Severity != "high" {
		t.Errorf("migrations_touched severity = %q, want high", got["migrations_touched"].Severity)
	}
}

func TestRiskFlags_DockerComposeByContent(t *testing.T) {
	// A devtools file that is not itself a compose file but wields it should
	// still raise docker_compose_touched via content scan (matches the
	// Makefile / ensure-postgres.sh case from the compose-precedence fix).
	files := []ChangedFile{
		{Path: "scripts/ensure-postgres.sh", Content: "docker compose -f docker-compose.yml up -d postgres"},
		{Path: "Makefile", Content: "COMPOSE := docker compose -f docker-compose.yml"},
	}
	got := flagNames(RiskFlags(files))
	flag, ok := got["docker_compose_touched"]
	if !ok {
		t.Fatal("expected docker_compose_touched to be raised by content scan")
	}
	if len(flag.Evidence) != 2 {
		t.Errorf("docker_compose_touched evidence = %v, want 2 files", flag.Evidence)
	}
}

func TestRiskFlags_GeneratedCode(t *testing.T) {
	files := []ChangedFile{
		{Path: "server/pkg/db/generated/agent.sql.go", Content: "// Code generated by sqlc. DO NOT EDIT."},
	}
	got := flagNames(RiskFlags(files))
	if _, ok := got["generated_code_touched"]; !ok {
		t.Error("expected generated_code_touched to be raised")
	}
}

func TestRiskFlags_DependencyManifest(t *testing.T) {
	files := []ChangedFile{
		{Path: "package.json"},
		{Path: "pnpm-lock.yaml"},
		{Path: "server/go.mod"},
	}
	got := flagNames(RiskFlags(files))
	flag, ok := got["package_dependency_touched"]
	if !ok {
		t.Fatal("expected package_dependency_touched to be raised")
	}
	if len(flag.Evidence) != 3 {
		t.Errorf("package_dependency_touched evidence = %v, want 3", flag.Evidence)
	}
}

func TestRiskFlags_DocsOnly(t *testing.T) {
	files := []ChangedFile{
		{Path: "README.md"},
		{Path: "docs/guide.mdx"},
	}
	got := flagNames(RiskFlags(files))
	if _, ok := got["docs_only"]; !ok {
		t.Error("expected docs_only to be raised for a docs-only diff")
	}
	if _, ok := got["tests_missing_for_code_change"]; ok {
		t.Error("docs-only diff must not raise tests_missing_for_code_change")
	}
}

func TestRiskFlags_CodeWithTestsDoesNotFlagMissingTests(t *testing.T) {
	files := []ChangedFile{
		{Path: "packages/core/api/client.ts"},
		{Path: "packages/core/api/client.test.ts"},
	}
	got := flagNames(RiskFlags(files))
	if _, ok := got["tests_missing_for_code_change"]; ok {
		t.Error("code change accompanied by a test must not raise tests_missing_for_code_change")
	}
}

func TestRiskFlags_LargeDiff(t *testing.T) {
	files := make([]ChangedFile, largeDiffThreshold)
	for i := range files {
		files[i] = ChangedFile{Path: "docs/file" + string(rune('a'+i%26)) + ".md"}
	}
	got := flagNames(RiskFlags(files))
	if _, ok := got["large_diff"]; !ok {
		t.Errorf("expected large_diff to be raised at %d files", largeDiffThreshold)
	}
}

func TestBuildReport_Shape(t *testing.T) {
	files := []ChangedFile{
		{Path: "server/internal/middleware/auth.go"},
		{Path: "CONTRIBUTING.md"},
	}
	r := BuildReport("origin/main", "HEAD", files)
	if r.BaseRef != "origin/main" || r.HeadRef != "HEAD" {
		t.Errorf("refs not preserved: %+v", r)
	}
	if len(r.ChangedFiles) != 2 {
		t.Errorf("changedFiles = %v, want 2", r.ChangedFiles)
	}
	if _, ok := r.Subsystems["security_auth"]; !ok {
		t.Error("expected security_auth subsystem")
	}
	if _, ok := r.Subsystems["docs"]; !ok {
		t.Error("expected docs subsystem")
	}
	if r.Summary == "" {
		t.Error("summary should not be empty")
	}
}
